# Generated by Django 4.2.27 on 2026-01-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='modalidad',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academico.modalidad'),
        ),
    ]
