# Generated by Django 4.2.27 on 2026-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_carrera_options_alter_modalidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
