# Generated by Django 4.2.27 on 2026-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_carrera_nombre_alter_modalidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado activo'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de carrera'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado activo'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de modalidad'),
        ),
    ]
